### ISSUE TITLE
colored button text unreadable

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI-Meteor#13]
Hey, Frederic!
There is strange code generated in `\definitions\elements\button.import.less`:

``` css
.ui.green.buttons .button:active,
 .ui.green.button:active {
   background-color: @greenDown;
   color: @greenTextColor;
   text-shadow: @greenTextShadow;
 }
```

in vanilla SUI:

``` css
{
   color: white;
   text-shadow: none;
 }
```
